name: "🐞 Bug Report"
description: "Report a bug to help us improve"
labels: ["🐛bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Guidelines for Bug Reports
        Detailed bug descriptions help us resolve issues faster.
  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of the bug.
      placeholder: Describe the problem in detail.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug in detail.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Check '....'
        4. Error occurs
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Explain what should have happened if it worked correctly.
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: Detail the actual outcome.
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system did the issue occur on?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (Other)
        - macOS
        - Windows
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: shell
    attributes:
      label: Shell Used
      description: Which shell are you using?
      options:
        - Bash
        - Zsh
        - Fish
        - PowerShell
        - CMD
        - Other
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots
      description: Add any error messages or screenshots if available.
      render: shell
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information about the problem.
      placeholder: Feel free to write any other relevant details about this bug. 