name: "✨ Feature Request"
description: "Suggest an idea for a new feature"
labels: ["✨feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Guidelines for Feature Requests
        Please describe your new feature idea in detail.
  
  - type: textarea
    id: description
    attributes:
      label: 📄 Description
      description: Provide a detailed description of the new feature.
      placeholder: The more detail, the better!
    validations:
      required: true
  
  - type: textarea
    id: todo
    attributes:
      label: ✅ Tasks
      description: List the tasks as checkboxes.
      placeholder: |
        Break it down as much as possible!
        Example:
        - [ ] Implement feature A
        - [ ] Write test code
        - [ ] Document
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or approaches?
      placeholder: If you've considered other methods, please share them.
  
  - type: textarea
    id: references
    attributes:
      label: 🙋🏻 References
      description: Please provide any relevant references.
      placeholder: Attach links, screenshots, etc. 